### ISSUE TITLE
Run individual sample from IntelliJ - Module javafx.graphics not found

### ISSUE THREAD

**Issue by Michael-Hayes-01** [fair-acc/chart-fx#668] opened 2024-05-25 10:42 UTC
**Describe the bug**
When running individual sample in IintelliJ the following error occurs:
Error occurred during initialization of boot layer java.lang.module.FindException: Module javafx.graphics not found

I'm new to javafx and this is the first time trying the chartfx project.
The ChartFxSampler main method runs ok from the IDE and also from the cmd line.
Can you please explain what I'm missing?

Thanks

**To Reproduce**
- clone the chartfx repo
- follow mvn build steps
- mvn refresh in IDE
- rebuild project
- run  FinancialAdvancedCandlestickSample
- edit the vm options to add the recommended VM add options etc
 

**Environment:**
 - OS: Windows 11 Home
 - Java version: 17.0.3
 - JavaFx version: 16
 - ChartFx version: [master]

**Comment by Michael-Hayes-01** [comment] 2024-05-25 10:43
IntelliJ IDEA 2023.3.6

**Comment by wirew0rm** [comment] 2024-05-25 12:18
Hey and welcome to chart-fx!

This is actually not a bug but just the way javafx and the java module system work. The key difference between the Sample Launcher and the individual samples is that the former does not extend the javafx.Application class but instead just calls a static loader function from javafx. The static loader then loads a class extending javafx.Application but has the chance to tell the java module system that it needs access to the javafx.graphics module before loading the class that then in it's static initialisation calls methods from that module. At least that's my understanding of what is happening.

For calling individual samples you have 2 options: either change the run configuration to have the appropriate [module parameters](https://github.com/fair-acc/chart-fx?tab=readme-ov-file#javafx-jvm-command-line-options), or rund them via the [io.fair_acc.sample.LaunchJFX](https://github.com/fair-acc/chart-fx/blob/main/chartfx-samples/src/main/java/io/fair_acc/sample/LaunchJFX.java) helper class, giving the class name of the sample as a command line argument. This class also has some documentation and links as to how this works and how you can setup idea to always run the currently active class.

Some of this could probably be made easier if chartfx was properly modularized. The last time I tried to do that I got the impression that it's not possible due to some of our dependencies not being modularized, but it was recently pointed out to me that that shouldn't be a problem, so I might give this another try when i find the time. I'd also welcome PR's in that direction if someone is familiar with the module system and wants to give that a try.

I'll close this, but feel free to ask further questions or reopen if this doesn't work for you.

**Closed by wirew0rm** 2024-05-25 12:18 UTC
Labels: not a bug

**Comment by Michael-Hayes-01** [comment] 2024-05-25 12:49
hi

Thanks for your quick response.

Part of my efforts to get started with JavaFx I created a new intelliJ project:
File -> new -> JavaFx Application

This project uses a file at root to specify various modules called module-info.java.
(I suspect this file is used by the <artifactId>javafx-maven-plugin</artifactId>, but I've not confirmed that yet)

In this project it's possible to start an application in a main and call 'launch(args)' and I was able to run a simple line chart.

Here is the format of the module-info.java file, which may possibly be of use if there is an effort to use this approach:

module com.example.javafx {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
...
    requires io.fair_acc.chartfx;
...
    opens com.example.javafx to javafx.fxml;
    exports com.example.javafx;
}

I'll try your suggestions now on how to run the samples now.

Thanks again

**Comment by wirew0rm** [comment] 2024-05-25 13:00
I don't know if the javafx-maven plugin also does anything with the file, but the module-info.java file belongs to the JPMS/jigsaw java module system that was introduced with java 9.

**Comment by Michael-Hayes-01** [comment] 2024-05-25 13:49
hi, 

I was able to run using the LaunchJFX.java class - thanks for this.

The above is probably enough for me to be getting on with for now.

Running using the intelliJ VM options however was not ok, it appears to need the module path. Without the module path the Module javafx.graphics not found, however with the path there are few errors:

superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x21b933d5) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x21b933d5

The modules are in the mvn repo is its not clear why the module path is required. Here are the VM options:

--module-path=D:/app/javafx/javafx-sdk-22.0.1/lib --add-modules=javafx.graphics,javafx.graphics,javafx.fxml,javafx.media --add-reads javafx.graphics=ALL-UNNAMED --add-opens javafx.controls/com.sun.javafx.charts=ALL-UNNAMED --add-opens javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED --add-opens javafx.graphics/com.sun.javafx.iio=ALL-UNNAMED --add-opens javafx.graphics/com.sun.javafx.iio.common=ALL-UNNAMED --add-opens javafx.graphics/com.sun.javafx.css=ALL-UNNAMED --add-opens javafx.graphics/javafx.scene=ALL-UNNAMED  --add-opens javafx.base/com.sun.javafx.runtime=ALL-UNNAMED --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED

Thanks
