### ISSUE TITLE
Cannot resolve plugin io.fair-acc:generate:master-SNAPSHOT

### ISSUE THREAD

**Issue by UtilityAcc** [fair-acc/chart-fx#535] opened 2022-07-23 05:56 UTC
After cloning repo there is following errror, very sad((

Cannot resolve plugin io.fair-acc:generate:master-SNAPSHOT

Also problems in POM, not found following plugins:

org.sonatype.plugins
nexus-staging-maven-plugin
1.6.4

org.apache.maven.plugins
maven-gpg-plugin
{version.maven-gpg-plugin}

**Comment by clisztian** [comment] 2022-09-23 13:21
Yep, I had the same problem actually with this latest repo. You could try the previous version. 
Which IDE are you using? DId you try using the Eclipse build instructions?

**Comment by protogenes** [comment] 2023-09-28 08:40
The branch is called `main` so the version must be `main-SNAPSHOT`
This should be fixed in the docs

**Comment by wirew0rm** [comment] 2023-09-29 16:19
I updated the docs to be in line with the latest 11.3.0 release, the master -> main branch move and the new maven coordinates. Sorry for the confusion during the time between 11.27 and 11.3.0, now everything should be in line again.

Since the repo builds in the CI, I assume that the original builds have to somehow differ from what is happening in the CI, but without information about which IDE you are using it's difficult to see what's going on here.

I'll close this for now since I cannot reproduce locally, feel free to reopen with additional information.

**Closed by wirew0rm** 2023-09-29 16:19 UTC
