### ISSUE TITLE
A vertical axis problem when using contour plot

### ISSUE THREAD

**Issue by clisztian** [fair-acc/chart-fx#549] opened 2022-10-10 17:45 UTC
When using the contour plots, there seems to be a vertical axis bug when enlarging vertically (which works fine), and then when shrinking back down. To easily reproduce, just try the following with your WaterfallPerformanceSample in your chart.samples. 

At first, everything is fine plot/functionality wise when launched. But then vertically increase height of window, then go back down to default size. You'll lose the x-axis.  I would expect that the contour chart stretches/shrinks vertically and fits according to the window size, similar to all other chart types, as well as horizontal stretching/shrinking works fine as expected.

Thanks for your help in advance. Fantastic library nonetheless!

![Screenshot from 2022-10-10 19-35-28](https://user-images.githubusercontent.com/3885050/194923420-ee2f03dd-65d9-4e8f-a99f-08222f9e98f3.png)

**Environment:**
 - OS: [e.g. Ubuntu 20.04]
 - Java version: openjdk 11
 - JavaFx version: 11
 - ChartFx version: [master, 11.2.2, ...]

**Comment by wirew0rm** [comment] 2022-10-14 07:50
Thanks for the report, iirc we have encountered this problem once already ourselfes, iirc it can be circumvented by not adding the color scale (may or may not be an option for you), but I was unsuccessfull in finding the root cause of this layouting problem. I'll have another look as it also relates to #529.

**Comment by wirew0rm** [comment] 2023-08-09 08:51
Seems to be fixed in #592, at least I cannot reproduce the problem in the sample. I'm closing this for now, feel free to retest with main (since we are in preparation for the major x.3 release, there are some changes in eg package names and some things are still moving it might make sense to wait for the release before upgrading) and reopen if the problem is still present.

**Closed by wirew0rm** 2023-08-09 08:51 UTC
